### ISSUE TITLE
Sorry, no tabbar, not perfect

### ISSUE THREAD

**Issue by xiaohange** [fahidattique55/FAPanels#1]
Sorry, no tabbar, not perfect

**Comment by fahidattique55** [comment]
Hi xiaohange,

FAPanels also works perfect in UITabBarController applications. I have tested it many times. Can you please mention any example in which you are facing issue ? It would be a fun if you need some extra feature in FAPanels.

Thank you

**Comment by fahidattique55** [comment]
xiaohange,

You can use FAPanels with TabBar application in these ways.

1. Set centerVC of FAPanelController a UITabBarController.
2. Set rootVC (index 0) of a UITabBarController a FAPanelController.

Both of these works perfect and the main thing here is that you have to be careful about the transitions of FAPanel Controller and UITabBarController. These two are both separate things.

For case 1,

Changing center panel VC will replace tabbatcontroller with a new controller you will set. you will have no access over tabbatcontroller through FAPanels.


For case 2,

Changing center panel VC will replace visible center controller of FAPanels with specified transition but your Tab bar controller will be pointing towards the same index controller (let say 0) which was visible before FAPanels transition.


Please feel free to ask any thing regarding FAPanels.

Thanks
