### ISSUE TITLE
(Request) FAPanelDelegate

### ISSUE THREAD

**Issue by droni89** [fahidattique55/FAPanels#11]
Might be useful to create a delegate for FAPanelController:

 public protocol FAPanelControllerDelegate: class{
    
    func centerPanelWillBecomeActive()
    func leftPanelWillBecomeActive()
    func rightPanelWillBecomeActive()
    
    func centerPanelDidBecomeActive()
    func leftPanelDidBecomeActive()
    func rightPanelDidBecomeActive()
}

**Comment by fahidattique55** [comment]
Hi droni89,

I will add it soon.

Thanks & regards

**Comment by fahidattique55** [comment]
Hi droni89,

The requested feature has been added. Please have a look into it and let me know in case you have any query.

I always welcome the new feature requests.

Thanks & Regards

**Comment by droni89** [comment]
Thanks for that!

Having a few Issues:

1. The delegate var in your FAPanelController class needs to be an open var because when the delegate is implemented in another class the delegate variable needs do be initialised such that 
panel?.delegate = self

This currently raises an error that FAPanelController has no such variable

2. Implementing the delegate requires stubs for each of the delegate methods to be added, even if they are not being used. A way around this is to write an extension (this creates a default implementation):

Extension FAPanelStateDelegate{
func centerPanelWillBecomeActive(){}
func leftPanelWillBecomeActive(){}
func rightPanelWillBecomeActive(){}

func centerPanelDidBecomeActive(){}
func leftPanelDidBecomeActive(){}
func rightPanelDidBecomeActive(){}

**Comment by fahidattique55** [comment]
Hi droni89,

Thanks for letting me know about the issues. I appreciate you kind concerns. The issue is fixed as you have suggested.

Thanks & Regards
