### ISSUE TITLE
Panel Delegates responses are slow

### ISSUE THREAD

**Issue by djaygit** [fahidattique55/FAPanels#12]
Not sure if it's only me

Delegate methods are running called for the first few times. 

and

let panel = FAPanelController() doesn't work, have to use (coder: ..)

**Comment by fahidattique55** [comment]
Hi djaygit,

I didn't get your point about delegate. Can you please explain it ?

FAPanelControll is a subclass of UIViewController. The init() is not a designated initialiser. That is why you can not make its object like  FAPanelController(). You can use it with coder or nib. I prefer using it with storyboards. That is the most simplest way of integrating it.

**Comment by fahidattique55** [comment]
It would be good if you can also tell me the reason you are using the FAPanelController() ?

**Comment by djaygit** [comment]
The delegate methods FAPanelStateDelegate
```
 func leftPanelWillBecomeActive() 
 func centerPanelWillBecomeActive()
```
are not called instantly, let me explain
when the app starts, if i open side panel, then leftPanelWillBecomeActive gives no response
neither centerPanelWillBecomeActive.

But after few tries they start responding

get it?

**Comment by fahidattique55** [comment]
Hi djaygit,

I have tested the delegates and its responding me to specified functions every time. Can you please verify the delegate is not nil while you are expecting the delegate methods to be called?

Please let me know if you face the issue again.

Thanks & Regards
