### ISSUE TITLE
Right panel position

### ISSUE THREAD

**Issue by vCrespoP** [fahidattique55/FAPanels#14]
Any option to get the behavior already defined for: 

> Left panel position (front/back) to center panel

...but for right panel?

Thanks for this useful implementation!

**Comment by fahidattique55** [comment]
Hi vCrespoP,

When I will get some free time I will add this feature as well.

Thanks & Regards

**Comment by fahidattique55** [comment]
Hi vCrespoP,

Your requested feature has been added. Please have a look into it.

Thanks & Regards
