### ISSUE TITLE
Could not cast value of type 'UIViewController' to FAPanels

### ISSUE THREAD

**Issue by djaygit** [fahidattique55/FAPanels#17]
let panel = AppStoryboard.Dashboard.instance.instantiateViewController(withIdentifier: "fapanel") as! FAPanelController
                let center = AppStoryboard.Dashboard.instance.instantiateViewController(withIdentifier: "tabbarnav")
                let left = AppStoryboard.Drawer.instance.instantiateViewController(withIdentifier: "leftdrawervc")
                panel.center(center).left(left)
                let appD = UIApplication.shared.delegate as! AppDelegate
                appD.window?.rootViewController = panel
                appD.window?.makeKeyAndVisible()

Inherit Module from target is marked

**Comment by fahidattique55** [comment]
Hi djaygit,

Please uncheck the inherit module from target if you are using FAPanels via cocoapods. Set the module name as FAPanels and It should not be the name of your app target.

Thanks & Regards

**Comment by djaygit** [comment]
well i tried this and worked

let panel = FAPanelController()

**Comment by fahidattique55** [comment]
Yes, you can also use the code approach.
