### ISSUE TITLE
Problem with closed menu.

### ISSUE THREAD

**Issue by Viher-Sano** [fahidattique55/FAPanels#18]
When I call _openCenter(animated: true)_, the menu closes without animation and  the animation is opened broken.
Please add a method to the _closeMenu()_ that would work like something the user clicks on the central view.

![viber image](https://user-images.githubusercontent.com/7523104/31789011-55b56d8e-b519-11e7-9a51-8bf6c864ceee.jpg)

**Comment by fahidattique55** [comment]
Hi Viher-Sano,

I did not get your point of consideration. Can you please provide me some more info so that I can diagnose it fully and then I can resolve the issue you are facing ?

**Comment by Viher-Sano** [comment]
I need to add a button on the left menu which would close it. I used this method for openCenter(animated: true). But when you click on the menu button closed without animation. And with the subsequent calls the menu animation was not smooth as it was before calling the method openCenter(animated: true).
Correct it please, if possible, and add the method to closeMenu(animated: true).
