### ISSUE TITLE
Problem with closed menu.

### ISSUE THREAD

**Issue by Viher-Sano** [fahidattique55/FAPanels#19]
@fahidattique55
I need to add a button on the left menu which would close it. I used this method for _**openCenter(animated: true)**_. But when you click on the menu button closed without animation. And with the subsequent calls the menu animation was not smooth as it was before calling the method _**openCenter(animated: true)**_.
Correct it please, if possible, and add the method to _**closeMenu(animated: true)**_.

**Comment by fahidattique55** [comment]
@Viher-Sano 

According to you, openCenter(animated: true) is working fine right?  Do you want openCenter(animated: false) to work smooth as well ?

Can you share a sample project so that I can look into it ?

**Comment by Viher-Sano** [comment]
The project is your example, in which the method of **openCenter(animated: true)** is called instead of the transitions(didSelectRowAt indexPath). At the same time menu closes without animation.

[Video](https://drive.google.com/open?id=0B2PM85mu-bKrc3FuQ1Y4Q3NPaVU)

**Comment by fahidattique55** [comment]
@Viher-Sano 

Thanks for reporting the issue. It was a great catch. Although the relevant methods were implemented already but was not proper mentioned any where. openCenter(animated:) was for left panel position on back and slideLeftPanelOut(animated:) function was for left panel position on top.

If you would have call this function you won't have caught the issue. But I have added a generic function now. You can use that one. As you have suggested closeLeft() and closeRight() are added in v "0.3.5". Please update and let me know in case you face any issues again.

Thanks again for reporting the issue and Video was helpful btw.

Thanks & Regards

**Comment by Viher-Sano** [comment]
I tested it. Everything works.
Thank you also!
