### ISSUE TITLE
FAPanel configuration issue

### ISSUE THREAD

**Issue by kanuder** [fahidattique55/FAPanels#2]
i followed instructions step-by-step and integrated FApanel. I can see the left panel but facing issue when trying to change configuration of left menu. Thanks.
![screen shot 2017-08-01 at 2 38 12 pm](https://user-images.githubusercontent.com/6723767/28818244-2ed28fb0-76c8-11e7-9d4a-7a47a4a715d5.png)

**Comment by fahidattique55** [comment]
Hi kanuder,

Thanks for reporting the issue. The issue is resolved now. Please update the pod to v0.1.5 and try again.
