### ISSUE TITLE
Can't remove panel

### ISSUE THREAD

**Issue by xylys** [fahidattique55/FAPanels#20]
when I try to remove a panel: 

`panel!.left(nil)`

I get the following error:

> Nil is not compatible with expected argument type 'UIViewController'

**Comment by fahidattique55** [comment]
Hi xylys,

I have fixed the issue. Please update the pod to version "0.3.4".

Thanks & Regards

**Comment by xylys** [comment]
Works like a charm!

Thanks and keep up the good work!!
