### ISSUE TITLE
How close side menu and push to target ViewController from center viewController?

### ISSUE THREAD

**Issue by UzumakiAlfredo** [fahidattique55/FAPanels#21]
Hi there.

I want to tap a button on side menu then close the side menu and push to a new viewController from center viewController.

I could't set a delegate from center viewController to side menu class so I used NotificationCenter!

NotificationCenter works and I can close the side menu but pushing to new viewController programically does not work !

present new class modally works though.

Thank You.

**Comment by fahidattique55** [comment]
Hi @UzumakiAlfredo,

Can you please confirm that your centre viewController is in NavigationController ? If its in a NavigationController then it should work.

Thanks & Regards
