### ISSUE TITLE
About step 2 

### ISSUE THREAD

**Issue by GilisHugo** [fahidattique55/FAPanels#24]
I've already set the root window as FAPanel controller.
But when i'm trying to do step 2, 
i can't let rootController: FAPanelController = window?.rootViewController as! FAPanelController
because FAPanelController is a undeclared type.

I'm pretty like this pod and want to use it in my project.
Please let me know if there's any solution.
Best regard

**Comment by fahidattique55** [comment]
@GilisHugo,

You are mixing here the two mechanisms of using FAPanels.

## First Way

If you have already set the root window as FAPanel controller from **storyboard.** then you won't face any issue in,

`let rootController: FAPanelController = window?.rootViewController as! FAPanelController`


## Second Way

**Create a FAPanelController and set it as root of your window**

`let rootController = FAPanelController()`
`window?.rootViewController = rootController`

So these are the two ways to use it. Please let me know in case you face further issues integrating the library. Thanks for liking it. Hope you will enjoy using it :)

**Comment by theMoe** [comment]
I have the same error. If I add

`import FAPlane`

to AppDelegate.swift, I don't see the error anymore. But it doesn't work.

**Comment by fahidattique55** [comment]
@theMoe 

Can you please add some details about the issue you are facing with FAPanels? That would be helpful for me to diagnose.

Thanks

**Comment by theMoe** [comment]
@fahidattique55 I think import in AppDelegate is not the right way. The problem is, that Xcode doesn't provide the FAPaneController, when I try it to add it to a ViewController.

**Comment by ibolat38** [comment]
@fahidattique55 @theMoe @GilisHugo  Hello everyone, I have faced this problem. First I added 'FAPanles' on Cocoapods and then i just want to use 'leftMenuVC' ... On my project there is a ViewController as a 'UIViewController'.. I deleted it and I added 'FAPanelController' as a 'UIViewController' and i set it as a root.. but its still gives me error on Appdelegate < [here error](https://i.hizliresim.com/jy30qD.png) >

**Comment by fahidattique55** [comment]
@ibolat38 

Please add `import FAPanels` the FAPanels framework in the file you are using FAPanels.

**Comment by ibolat38** [comment]
@fahidattique55 I already add it but it still gives me same error. < [here FAPanelController](https://i.hizliresim.com/VrYXjn.png) >

**Comment by sMaq** [comment]
hi @fahidattique55 i am facing issue with your library. i have to use this side drawer after login screen so how can i use your side drawer withou appdelegate ? by without assigning it as a root view controller? any idea ?
