### ISSUE TITLE
Swift 3 @objc inference in Swift 4 mode is deprecated

### ISSUE THREAD

**Issue by theMoe** [fahidattique55/FAPanels#25]
Xcode shows me this warning:

`The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "FAPanel" target.
 `
Can you fix it?

**Comment by fahidattique55** [comment]
@theMoe 

Issue is resolved. Please have a look into updated pod.

https://cocoapods.org/pods/FAPanels

**Comment by theMoe** [comment]
Perfect! Thanks! I will try it.
