### ISSUE TITLE
Import file issue

### ISSUE THREAD

**Issue by Hamza-Brainplow** [fahidattique55/FAPanels#28]
Hi, i'm importing the FAPanels but it is showing an error that no such module. I have properly installed the pods but it is showing such issue. 
Second one i want to ask that in my centerVC how can i open LeftFAPanel in click of button and same with other View controllers just on click of a button?
It would be more better if u have a video tutorial also.

**Comment by Hamza-Brainplow** [comment]
Hi, i'm facing an issue in appdelegate.swift class. My code in appdelegate class is this,
 func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        
        let leftMenuVC: LeftVC = mainStoryboard.instantiateViewController(withIdentifier: "LeftVC") as! LeftVC
        
        let centerVC: CentralVC = mainStoryboard.instantiateViewController(withIdentifier: "CentralVC") as! CentralVC
        let centerNavVC = UINavigationController(rootViewController: centerVC)
        
        
        //  Set the Panel controllers with just two lines of code
        
        let rootController: FAPanelController = window?.rootViewController as! FAPanelController
        
        rootController.configs.panFromEdge = false
        rootController.configs.minEdgeForLeftPanel  = 70
        
         _ = rootController.center(centerNavVC).left(leftMenuVC)
        
        //  For Case 1 only
        window?.rootViewController = rootController
        
        return true
    }

When i run the app it crashes by showing this error,
`Unknown class _TtC12SideMenuDemo17FAPanelController in Interface Builder file.
2018-03-13 10:33:25.484182+0500 SideMenuDemo[12142:467374] Unknown class LeftVC in Interface Builder file.
Could not cast value of type 'UIViewController' (0x109cabca8) to 'SideMenuDemo.LeftVC' (0x1075293d0).
2018-03-13 10:33:25.484882+0500 SideMenuDemo[12142:467374] Could not cast value of type 'UIViewController' (0x109cabca8) to 'SideMenuDemo.LeftVC' `

My storyboard is like this,
<img width="1401" alt="screen shot 2018-03-13 at 10 36 27 am" src="https://user-images.githubusercontent.com/34932267/37324282-73498620-26aa-11e8-8006-bedecfd3b9d0.png">

**Comment by Hamza-Brainplow** [comment]
I have place a tab bar as my centralVC it open the first tab bar item but doesn't show tab bar at the bottom.

**Comment by fahidattique55** [comment]
@Hamza-Brainplow 

# No.1

> i'm importing the FAPanels but it is showing an error that no such module. I have properly installed the pods but it is showing such issue.

If you have installed the pods correctly and imported in the file you are using FAPanels, then just try to build the project with **Command + b** because some times the newly installed pods are in Red color under Pods in your workspace. Just give it a try and let me know in case you face issue again.

# No.2

> Second one i want to ask that in my centerVC how can i open LeftFAPanel in click of button and same with other View controllers just on click of a button?
It would be more better if u have a video tutorial also.

Please read this https://github.com/fahidattique55/FAPanels#openclose-panels 



# No.3

> Please share the code snippets so that I can look into details of it. For some work around please see #1 to understand the working of FAPanels with Tab bar controllers.

**Comment by Hamza-Brainplow** [comment]
Hi, thanks for ur response bro, i have tried your code for opening the Left FAPanel on click of a button. This is my second view controller in which i'm trying to open it but nothing is happening on click of button. This is my viewDidLoad method,
`override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationController?.isNavigationBarHidden = true
        
        panel?.configs = FAPanelConfigurations()
    }`

This is my button action,
`@IBAction func Menu(_ sender: Any) {
      panel?.openLeft(animated: true)
    }`
Its not working.

**Comment by fahidattique55** [comment]
@Hamza-Brainplow 

**There are two possibilities,**

### No.1 

Either the leftPanelVC is nil

### No.2 

Or the `panel` you are trying to get for using `openLeft(animated: true)` is nil

**Comment by fahidattique55** [comment]
@Hamza-Brainplow 

Are you able to diagnose the problem ?

**Comment by fahidattique55** [comment]
Closing issue as not activity response from @Hamza-Brainplow
