### ISSUE TITLE
Step of installation into an existing project

### ISSUE THREAD

**Issue by wizard699** [fahidattique55/FAPanels#29]
It's possibile to describe, step by step, the process to install and import into an existing project your fantastic FAPanels?

I've installed POD ..... ok.
But then which files I have to import in my project, starting for the projects FAPanels files?

Thanks in advance

**Comment by fahidattique55** [comment]
@wizard699 

Thank you for using FAPanels. Please follow this [step by step](https://github.com/fahidattique55/FAPanels#usage-3) guide.
