### ISSUE TITLE
carthage support?

### ISSUE THREAD

**Issue by nitrag** [fahidattique55/FAPanels#3]
Can you please add Carthage support?

**Comment by fahidattique55** [comment]
Hi nitrag,

Thanks for the suggestion. I will add Carthage support in it soon. Let me know in case you have any further suggestions.

Thanks & Regards

**Comment by zdenektopic** [comment]
+1 👍

**Comment by fahidattique55** [comment]
Hi zdenektopic,

Carthage support is added for FAPanels. Please have a look into it and enjoy. I appreciate you suggest me about Carthage. Please feel free to ask me more to add in FAPanels.

Thanks & Regards
