### ISSUE TITLE
Add sidemenu callback

### ISSUE THREAD

**Issue by pvn-anh-pham** [fahidattique55/FAPanels#30]
Hi!
This is very cool library and it was integrated into my application. That's great!
However, I would like to know when the side menu was closed or opened. For ex: The left menu contain so feature, that I dont want user to access right now, so everytime user try to open the menu, I want to notify user about that and recommend user to upgrade to paid version...
That is very handy to know when user close/open the side menu or event change side or center view. That help application can manage side menu completely 

Please think about that and if it could available in some update later, that would be awesome!!

Thank

**Comment by fahidattique55** [comment]
@pvn-anh-pham 

Thank you for the appreciation. You can handle this situation with the `FAPanelStateDelegate`. It gives you access when the left, right and centre panel has became active or not.
