### ISSUE TITLE
how to reload rootviewcontroller?

### ISSUE THREAD

**Issue by parth0072** [fahidattique55/FAPanels#31]
Hey 

I am using fapanels in my application it's working fine in my app.
but I implemented the localization in my app for localization we need to reload rootview controller to change the language without close the app.
I tried multiple ways to reload rootview controller but it's not working.

Any idea? please let me know if you have any idea of this??

Thanks :)

**Comment by fahidattique55** [comment]
@parth0072 

The simplest way to do this is register for an observer in your root class and when you change the localisation in-app then fire a notification and the observer will trigger a function call. You can add your business logic there.
