### ISSUE TITLE
Change dark overlay opacity with animation

### ISSUE THREAD

**Issue by Shamsiddin** [fahidattique55/FAPanels#33]
Hi,
I configured `FAPanel` to show dark overlay when left panel position is front
`configs.showDarkOverlayUnderLeftPanelOnTop = true`

But this overlay view appears/disappears without animation. I want to animate it's opacity depending on the left panel's distance from the edge (or while moving left panel with the finger).

How can I achieve this?
Thanks.

**Comment by Shamsiddin** [comment]
Hi @SeNeO 
I used this code snippet:

```
rootController.leftPanelPosition = .front
rootController.configs.showDarkOverlayUnderLeftPanelOnTop = true
```

But darkOverlayView appearing/disappearing immediately(without opacity animation) when you leave your finger. Is it possible to make it appear/disappear it with fade animation (smoothly)?

**Comment by usmantarar51** [comment]
Hi @Shamsiddin i appreciate this suggestion you made, working on it!

**Comment by fahidattique55** [comment]
@usmantarar51 

Can you please tell me how much time you anticipate more for this feature to be integrated in FAPanels ?

**Comment by usmantarar51** [comment]
Will give you a update soon.

**Comment by fahidattique55** [comment]
I have started working on this one as I have been receiving this feature requests from a lot of people. Lets do it 👍

**Comment by huanglins** [comment]
Is it ready for use？

**Comment by fahidattique55** [comment]
Yes, it's ready to use. Please install latest code.
