### ISSUE TITLE
Central Panel Need to hide the Menu ICONS

### ISSUE THREAD

**Issue by mekalasiva** [fahidattique55/FAPanels#35]

**Comment by mekalasiva** [comment]
How to hide the Central Panel choose hide the Left Menu and Right Menu icons.

**Comment by fahidattique55** [comment]
Hi @mekalasiva 

Just call the `openCenter(animated:Bool)` to open the existing centre panel.

**Comment by fahidattique55** [comment]
or if you want to change it then use below code,

```
        let panelVC = FAPanelController()
                homeVC = UIStoryboard.home.instantiateInitialViewController()
            _ = panelVC.center(homeVC!)
        window?.rootViewController = panelVC
```

**Comment by mekalasiva** [comment]
What is homeVC?is it any class method name?

**Comment by fahidattique55** [comment]
Any centre controller you want to assign to centre panel.

**Comment by fahidattique55** [comment]
Either a UIViewController, UINavigationController or a UITabBarController etc.
