### ISSUE TITLE
Xcode beta 5 Swift 4.2 - iOS 10.2 platform produces a crash

### ISSUE THREAD

**Issue by waelsaad** [fahidattique55/FAPanels#38]
Hi,

After creating a simple project, simply by referencing the framework using Carthage I am getting a crash, any ideas please?

dyld: Symbol not found: __T0BOWV
  Referenced from: /Users/r00tdvd/Library/Developer/CoreSimulator/Devices/245706A5-FD39-4288-B04D-202402D21E68/data/Containers/Bundle/Application/4E801E8F-F71E-4583-9816-52F718E68BBA/SavingGrace.app/Frameworks/FAPanel.framework/FAPanel
  Expected in: /Users/r00tdvd/Library/Developer/CoreSimulator/Devices/245706A5-FD39-4288-B04D-202402D21E68/data/Containers/Bundle/Application/4E801E8F-F71E-4583-9816-52F718E68BBA/SavingGrace.app/Frameworks/libswiftCore.dylib
 in /Users/r00tdvd/Library/Developer/CoreSimulator/Devices/245706A5-FD39-4288-B04D-202402D21E68/data/Containers/Bundle/Application/4E801E8F-F71E-4583-9816-52F718E68BBA/SavingGrace.app/Frameworks/FAPanel.framework/FAPanel

**Comment by fahidattique55** [comment]
Issue is fixed in newer version of pod. Please try with updated version.
