### ISSUE TITLE
How to disble side menu in another viewController ?

### ISSUE THREAD

**Issue by jerrypm** [fahidattique55/FAPanels#39]
I try to use setNavigationController in next viewController, I want to remove FAPanels in there, how can I fix it?

let vc = HomeViewController()
self.navigationController?.setViewControllers([vc], animated: true)

**Comment by fahidattique55** [comment]
@jerrypm 

Need some more information about what your controller hierarchy is ?

How you are using FAPanels ? If its assigned to root view controller of window then you need to change the root controller of window. But it would be better if you can share some more details.

Thanks & Regards
