### ISSUE TITLE
not found FAPanelController

### ISSUE THREAD

**Issue by Kitty555** [fahidattique55/FAPanels#41]
![error1](https://user-images.githubusercontent.com/30800688/44511863-be040b80-a6f3-11e8-8352-3d5de8c4d360.png)

Your module is very good. I think this is my fail. Please help me.
Thank you.

**Comment by fahidattique55** [comment]
@Kitty555 

You forgot to import FAPanel in the App Delegate file. Please try to add import line on top and then build the project.
