### ISSUE TITLE
How to open FAPAnnel inside ViewController not in app Delegate ??

### ISSUE THREAD

**Issue by MahmoudKhaled** [fahidattique55/FAPanels#46]
i set it in app delegate already when the user open app for the second time but when he open it for first time i want to open main screen from this button action and i git this error

<img width="1184" alt="screen shot 2018-10-21 at 5 14 53 pm" src="https://user-images.githubusercontent.com/10100880/47268747-0b1a2780-d555-11e8-9325-055ee5f4a794.png">

**Comment by penpens** [comment]
I'm stuck too...

**Comment by LongNguyenPTIT** [comment]
How can do it ?

**Comment by jerrychong25** [comment]
@MahmoudKhaled @penpens @fahidattique55 

Same issue here, after settings root window controller class as **FAPanelController**, it can successfully open in AppDelegate first time.

**AppDelegate Code:**
```
        NSLog("AppDelegate application() 1")

        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let leftMenuVC: LeftMenuVC = storyboard.instantiateViewController(withIdentifier: "LeftMenuVCIdentifier") as! LeftMenuVC
        let mainOnlineVC: MainOnlineVC = storyboard.instantiateViewController(withIdentifier: "MainOnlineVCIdentifier") as! MainOnlineVC

        NSLog("AppDelegate application() 2")

        //  Set the Panel controllers with just two lines of code
        let rootController: FAPanelController = window?.rootViewController as! FAPanelController
        rootController.center(mainOnlineVC).left(leftMenuVC)

        NSLog("AppDelegate application() 3")

        window?.rootViewController = rootController

        NSLog("AppDelegate application() 4")
```

However, when I open again for second time in **UIViewController**, it will failed with **Thread 1: signal SIGABRT** error, as per screenshot below:
![Screenshot 2019-07-26 at 6 02 44 PM](https://user-images.githubusercontent.com/15714095/61944175-a605cd80-afcf-11e9-8150-91b06eb68aee.png)

**UIViewControllerCode:**
```
        NSLog("LoginVC didLogin() application() 1")
                            
        let appDelegate = UIApplication.shared.delegate as? AppDelegate
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let leftMenuVC: LeftMenuVC = storyboard.instantiateViewController(withIdentifier: "LeftMenuVCIdentifier") as! LeftMenuVC
        let mainOnlineVC: MainOnlineVC = storyboard.instantiateViewController(withIdentifier: "MainOnlineVCIdentifier") as! MainOnlineVC
                            
         NSLog("LoginVC didLogin() application() 2")
                            
         //  Set the Panel controllers with just two lines of code
         let rootController: FAPanelController = appDelegate?.window?.rootViewController as! FAPanelController
         rootController.center(mainOnlineVC).left(leftMenuVC)
                            
         NSLog("LoginVC didLogin() application() 3")
                            
         appDelegate?.window?.rootViewController = rootController
                            
         NSLog("LoginVC didLogin() application() 4")
```

The logic flow is exactly the same, only writing style is different due to different files.

Could advise how to fix this issue?

Thanks.

**Comment by jerrychong25** [comment]
> @MahmoudKhaled @penpens @fahidattique55
> 
> Same issue here, after settings root window controller class as **FAPanelController**, it can successfully open in AppDelegate first time.
> 
> **AppDelegate Code:**
> 
> ```
>         NSLog("AppDelegate application() 1")
> 
>         let storyboard = UIStoryboard(name: "Main", bundle: nil)
>         let leftMenuVC: LeftMenuVC = storyboard.instantiateViewController(withIdentifier: "LeftMenuVCIdentifier") as! LeftMenuVC
>         let mainOnlineVC: MainOnlineVC = storyboard.instantiateViewController(withIdentifier: "MainOnlineVCIdentifier") as! MainOnlineVC
> 
>         NSLog("AppDelegate application() 2")
> 
>         //  Set the Panel controllers with just two lines of code
>         let rootController: FAPanelController = window?.rootViewController as! FAPanelController
>         rootController.center(mainOnlineVC).left(leftMenuVC)
> 
>         NSLog("AppDelegate application() 3")
> 
>         window?.rootViewController = rootController
> 
>         NSLog("AppDelegate application() 4")
> ```
> 
> However, when I open again for second time in **UIViewController**, it will failed with **Thread 1: signal SIGABRT** error, as per screenshot below:
> ![Screenshot 2019-07-26 at 6 02 44 PM](https://user-images.githubusercontent.com/15714095/61944175-a605cd80-afcf-11e9-8150-91b06eb68aee.png)
> 
> **UIViewControllerCode:**
> 
> ```
>         NSLog("LoginVC didLogin() application() 1")
>                             
>         let appDelegate = UIApplication.shared.delegate as? AppDelegate
>         let storyboard = UIStoryboard(name: "Main", bundle: nil)
>         let leftMenuVC: LeftMenuVC = storyboard.instantiateViewController(withIdentifier: "LeftMenuVCIdentifier") as! LeftMenuVC
>         let mainOnlineVC: MainOnlineVC = storyboard.instantiateViewController(withIdentifier: "MainOnlineVCIdentifier") as! MainOnlineVC
>                             
>          NSLog("LoginVC didLogin() application() 2")
>                             
>          //  Set the Panel controllers with just two lines of code
>          let rootController: FAPanelController = appDelegate?.window?.rootViewController as! FAPanelController
>          rootController.center(mainOnlineVC).left(leftMenuVC)
>                             
>          NSLog("LoginVC didLogin() application() 3")
>                             
>          appDelegate?.window?.rootViewController = rootController
>                             
>          NSLog("LoginVC didLogin() application() 4")
> ```
> 
> The logic flow is exactly the same, only writing style is different due to different files.
> 
> Could advise how to fix this issue?
> 
> Thanks.

Found the solution accidentally.

Change from 

`let rootController: FAPanelController = appDelegate?.window?.rootViewController as! FAPanelController`

to

`let rootController = FAPanelController()`

Then it will works successfully.
