### ISSUE TITLE
Rewrite access control from public to open

### ISSUE THREAD

**Issue by hamsternik** [fahidattique55/FAPanels#5]
In this issue, I just want to discuss an ability get access for each user of your framework to create custom subclasses inheriting from the `FAPanelController` class and override any method, which he/she prefer. 

It's quite simple, and I guess, it'll be such a cool way to interact with your framework if need.

**Comment by fahidattique55** [comment]
Hi hamsternik,

I agree with you and Its a great option for all users of FAPanels. I will update it soon.

Thanks

**Comment by hamsternik** [comment]
OK. If I'll have some free time today, I guess I'll make a PR with this fix.
