### ISSUE TITLE
I can't navigate user to desired viewcontroller

### ISSUE THREAD

**Issue by GokmenAkar** [fahidattique55/FAPanels#50]
First I must thank you for this elegant framework. The panel works fine, I can travel between viewControllers on the left menu, but the problem (or my struggle) starts when I try to navigate the user from the opened viewController to another viewController. I want to use the `present` method but I can't make it work.  When I use the `panel!.center(centerVC)` it presents weirdly(shown below).

![simulator screen shot - iphone se - 2018-11-28 at 09 11 22](https://user-images.githubusercontent.com/16048623/49132984-793dd100-f2ef-11e8-8ee4-56e8f2909905.png)

**Comment by PGandhi30** [comment]
@GokmenAkar @fahidattique55 
Is it possible to do navigate one controller to another controller?
How is possible for this library?

**Comment by fahidattique55** [comment]
Hey, If you want to present a controller with modal presentation style, then just use native `present(_ viewController: UIViewController)` method and it should work. If you want to move from one controller in centre panel then keep it as a `UINavigationController` and you will be able to use `push` and `pop` features.
