### ISSUE TITLE
Destroy left View Controller after close swipe?

### ISSUE THREAD

**Issue by filsv** [fahidattique55/FAPanels#52]
Hi, after first open of left panel probably it's cached. So after second opening of left panel viewDidLoad, viewDidAppear, viewWillAppear, etc.. not called, please help.

**Comment by sw-tt-anjalibhimani** [comment]
Hi, Have you got any solution?

**Comment by fahidattique55** [comment]
Hey, please use `FAPanelStateDelegate` to manage the states of FAPanel.
