### ISSUE TITLE
UITabBarController ?

### ISSUE THREAD

**Issue by ghimireprashant** [fahidattique55/FAPanels#58]
can you please add demo with UITabBarController..

**Comment by jbarros35** [comment]
I don't understand how to do that either.
my app doesn't just opens at main screen with the menu, it must first pass through a login setup in order to check it out.

**Comment by ErAshu** [comment]
any update? I have to use like @jbarros35  uses.
First login process complete then jump on TabBarcontroller with side menu.

**Comment by fahidattique55** [comment]
Hey,

You can create a FAPanel controller in your app from anywhere. @ErAshu in your case when user presses the login button then you can create a FAPanel controller using code (or you can use storyboards as well) and assign it as root view controller of your Applications's key window.

For tab bar, @ghimireprashant - there are a lot of scenarios/ways to use FAPanels with tabbar. It totally depends on your usage.

Simple use case: Embed a tab bar controller in FAPanel controller as centre view controller. For this one, just set the centre as a UITabBarController.

Complex use cases: You need to use FAPanel in all tabs of a UITabBarController. Not sure why someone will have this scenario as its complex to manage these many controller hierarchies but you can achieve this by setting each tab as FAPanel controller class.
