### ISSUE TITLE
How to push View when any option selected from menu?

### ISSUE THREAD

**Issue by Piyush08** [fahidattique55/FAPanels#59]
Hello,
Can you add example for this? I can't see any option to push from menu.

Thank you,

**Comment by Gajalakshmi94** [comment]
Same issue , I too have faced.Please share the possible solution to solve this issue

**Comment by JhonnyTawk** [comment]
same as me please when you find a solution let me know

**Comment by fahidattique55** [comment]
Hey,

There are two ways to do this if you are talking about changing centre panel on left menu click event,

1. 
```
panel!.center(centerNavVC, afterThat: {
    print("Executing block after changing center panelVC From Left Menu")
})
```

2. 
```
open func openCenter(animated:Bool)
```

**Comment by fahidattique55** [comment]
If you guys are trying to push some new controller in centre panel or left panel then you need to manage this using UINavigationController.
