### ISSUE TITLE
Create an example project

### ISSUE THREAD

**Issue by hamsternik** [fahidattique55/FAPanels#6]
Working with your framework, I guess it will be amazing if a new user will be able not just look at README throughout working with `FAPnels`, but if he/she could download a small demo project with some easy-to-implement features and can touch it deeper, interacting and adapting to work with the framework in parallel.

**Comment by fahidattique55** [comment]
When you will clone 'FAPanels', you will get the example project in it. In example project, one can interact with all features and touch deeper as well.

**Comment by fahidattique55** [comment]
Other than that, if you have any suggestion then please share it. It would be a great fun to add on new things in 'FAPanels' to make people's life more easier. 

Lastly, I do appreciate the suggestion you give me earlier. 

Thank you

**Comment by hamsternik** [comment]
@fahidattique55 yes, I find example classes, which are you talking about. 
But the preferable way is to make a separate project in the isolated folder named smth like `FAPanelsExample`. It will be more clear for each of new user, IMO.

**Comment by hamsternik** [comment]
OK. for now I'm using your framework, but after that, I think about some new example project. 
BTW, I think first of all it's necessary to isolate your existed example project from the library source code.

**Comment by fahidattique55** [comment]
Hey hamsternik,

I have updated the access control level to 'open'. So that you can subclass FAPanels classes. Also for example project, feel free to contribute as you want. Contributions are always welcome for FAPanels.

Thanks & Regards
