### ISSUE TITLE
Integration with Swift 5

### ISSUE THREAD

**Issue by QasimnaveedJem** [fahidattique55/FAPanels#60]
SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'FAPanels')
I have just added Swift 5 toolchain in xcode 10.1

**Comment by QasimnaveedJem** [comment]
@fahidattique55 
I have updated pod to version 1.0.3. i am still facing the same issue

in my pod file "pod 'FAPanels', '~> 1.0.3'"

![Screen Shot 2019-04-10 at 9 57 08 AM](https://user-images.githubusercontent.com/49440684/55852705-7abdb680-5b77-11e9-9db7-338329c4bdce.png)
![Screen Shot 2019-04-10 at 10 01 19 AM](https://user-images.githubusercontent.com/49440684/55852756-a2ad1a00-5b77-11e9-8ff1-440fcf7b46d4.png)

**Comment by fahidattique55** [comment]
Try with the following code only. Remove the 1.0.3
> pod 'FAPanels'

**Comment by jerrychong25** [comment]
**pod 'FAPanels'** is working on **Xcode 10.**2

**Comment by QasimnaveedJem** [comment]
thanks for  your email
actually i moved from that project and got busy so that i can't reply
