### ISSUE TITLE
Username Not change when i logout and login Again different user

### ISSUE THREAD

**Issue by isaacraja15** [fahidattique55/FAPanels#66]
Hi Bro,

I try your Pod in my project. i have one Question.

Im using username and Profile pic in menu top view using userdefault. when i start app user name working fine but when i logout and login another user but the menu still showing old user name. Did you add any cache for menu ? Kindly Help me. 
![Screenshot 2019-05-13 at 7 57 44 PM](https://user-images.githubusercontent.com/44321070/57629907-3e3c0b00-75ba-11e9-82e7-62524c6c870c.png)
![Screenshot 2019-05-13 at 8 05 29 PM](https://user-images.githubusercontent.com/44321070/57630078-93781c80-75ba-11e9-8842-5e0b2cc649cf.png)
![Screenshot 2019-05-13 at 8 05 58 PM](https://user-images.githubusercontent.com/44321070/57630080-93781c80-75ba-11e9-89e6-1926863055d3.png)

 Thank you

**Comment by fahidattique55** [comment]
@isaacraja15 No, there is no cache mechanism added for side menu. Make sure to instantiate new left menu controller when you are logging in the app or update the UI using `FAPanelStateDelegate`.
