### ISSUE TITLE
Left side menu right slide will open WebView website own side menu as well?

### ISSUE THREAD

**Issue by jerrychong25** [fahidattique55/FAPanels#67]
Hi all,

I would like to add FAPanels Left Side Menu into my iOS app, which already have WebView (Loaded with a website) in the app.

After added successfully, I tried to right slide from screen, as per below:
![Screenshot 2019-07-31 at 3 40 53 PM](https://user-images.githubusercontent.com/15714095/62193448-585fdb00-b3aa-11e9-8d9c-a89293910ab4.png)

In the end, it will trigger FA Panels left side menu as well as website own side menu too. In total 2 side menus are displayed on my iOS app.

Expected Behaviour (1 Side Menu):
![Screenshot 2019-07-31 at 3 43 08 PM](https://user-images.githubusercontent.com/15714095/62193434-5138cd00-b3aa-11e9-9f40-3ae50f5c6738.png)

Actual Behaviour (2 Side Menu - FA Panels Side Menu on top of WebView Side Menu):
![Screenshot 2019-07-31 at 3 43 08 PM](https://user-images.githubusercontent.com/15714095/62193434-5138cd00-b3aa-11e9-9f40-3ae50f5c6738.png)

![Screenshot 2019-07-31 at 3 43 20 PM](https://user-images.githubusercontent.com/15714095/62193524-82190200-b3aa-11e9-9bc8-90d790c91474.png)

Is there any ways to set any hand gesture will always trigger only FA Panels Side Menu (on top of WebView)?

Thanks.

**Comment by fahidattique55** [comment]
@jerrychong25 you can disable webview's gesture to so the pan gestures of FAPanels will not have any conflict with it.
