### ISSUE TITLE
Status bar change to dark

### ISSUE THREAD

**Issue by JhonnyTawk** [fahidattique55/FAPanels#69]
in my app it's based on a black background so I use status bar style = .light when I implement the FAPanels it's always black.
 I am using the latest FAPanels Pod

I tried setting  
```
override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
```

and 
`setNeedsStatusBarAppearanceUpdate()`

and this issue persists 
**How to fix this issue?**

**Comment by fahidattique55** [comment]
```
    open override var preferredStatusBarStyle: UIStatusBarStyle {
        
        switch state {
        case .center:
            return centerPanelVC!.preferredStatusBarStyle
        case .left:
            return leftPanelVC!.preferredStatusBarStyle
        case .right:
            return rightPanelVC!.preferredStatusBarStyle
        }
    }
```

@JhonnyTawk 

FAPanels uses the `preferredStatusBarStyle ` of the visible controller. Please make sure debugger is going into this function. I hope it will work. If not then let me know I'll try to sort it out for you.
