### ISSUE TITLE
FAPanels pod doesnt exist

### ISSUE THREAD

**Issue by DavidKababyan** [fahidattique55/FAPanels#7]
Hey, the pod doesnt exist, please check that out.

**Comment by fahidattique55** [comment]
Hi DavidKababyan,

I have tested it and I am able to install the 'FAPanels' from cocoapods.

![screen shot 2017-08-06 at 5 52 35 pm](https://user-images.githubusercontent.com/12518061/29003451-62d39e42-7ad0-11e7-8708-b72a38c3d081.png)

I hope the cocoapods server was down or may be your master cocoapods repo was not updated. Please let me know in case you face any issues.

Thanks & Regards

**Comment by fahidattique55** [comment]
Also, Please make sure you can see the 'FAPanels' cocoapods page.

https://cocoapods.org/?q=FAPanel

**Comment by DavidKababyan** [comment]
Hey, thx for quick reply!
I could see it cocoapods website but it wasnt working on cocoapods 1.2.
I updated to 1.3 version and it worked.

Thanks a lot!

**Comment by fahidattique55** [comment]
Hi DavidKababyan,

You are always welcome. Please let me know in case you have any query or you face any issue.

Thanks & Regards
