### ISSUE TITLE
Pushing from menu won't get back

### ISSUE THREAD

**Issue by JhonnyTawk** [fahidattique55/FAPanels#72]
I implemented the menu in my app the center View is a TabbarController.
I open the menu I click on an item I go to the view and then I want to return to the main view popViewController and popToRootViewController does not work.
what to do ?

**Comment by fahidattique55** [comment]
Can you share the code and view controller hierarchy when you are clicking on an item to go to some view? As I believe its just the controller hierarchy issue in your side.
