### ISSUE TITLE
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

### ISSUE THREAD

**Issue by chumendaiyibeigouqi** [fahidattique55/FAPanels#74]
Hi,I used xcode 11, ios 13, to create a new project, run it on the device, and encountered an error. Projects created in Xcode10 will not be encountered using FAPanels.
Xcode helped me locate it here.

> let rootController: FAPanelController = window?.rootViewController as! FAPanelController

> error: launchOptions = ([UIApplication.LaunchOptionsKey : Any]?)	nil

**Comment by fahidattique55** [comment]
Hi @chumendaiyibeigouqi 

Can you please make sure the root controller in main storyboard is FAPanelController? 

If yes then please share some more details how are you using it.
