### ISSUE TITLE
No configurable or customizable

### ISSUE THREAD

**Issue by jbarros35** [fahidattique55/FAPanels#75]
I can't understand why we are obligated to change the AppDelegate, there are no better solution for this?
I mean, most applications need a first login storyboard and only after opens a main view with probably a UITabController.
Your solution looks no much flexible for most of us.

**Comment by fahidattique55** [comment]
Hey @jbarros35 

It's not necessary to change it in AppDelegate. You can use it from main storyboard as well. I'm planning to add few examples on how to use FAPanels in different scenarios. I'll keep you posting here. Not sure how long its gonna take but will be out soon.
