### ISSUE TITLE
Push and pop from left Menu 

### ISSUE THREAD

**Issue by gurwinder88** [fahidattique55/FAPanels#76]
I have home controller that is my HomeVC and then open LeftMenu Using panel?.openLeft(animated :true) 

But the issue is pushViewController is not working on leftMenu only panel?.center(viewcontroller) is working and not able to pop back to my HomeVc.  Please help it out.

**Comment by gurwinder88** [comment]
Anybody is there to maintain the library ?

**Comment by fahidattique55** [comment]
@gurwinder88 

I've two understandings of what you are asking for.

1. You're trying to push a controller in left panel (Left panel should be having a navigation controller to do that)
2. You're trying to open centre from left panel (use `openCenter(animated:Bool)` or change the centre panel to show a new centre controller using `center( _ controller: UIViewController, afterThat completion: (() -> Void)?)`)
