### ISSUE TITLE
Great library. Thanks for sharing

### ISSUE THREAD

**Issue by steve21124** [fahidattique55/FAPanels#8]
Thanks for sharing the library. just info. Warning in xcode.
warning from xcode
"the use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and disable Swift 3 @objc inference."

**Comment by fahidattique55** [comment]
Hi steve21124,

I will update it soon.

Thanks & Regards
